name: {{APP_NAME}}
description: "Generated project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  sizer: ^3.1.3
  get: ^4.7.2
  flutter_dotenv: ^6.0.0
  flag: ^7.0.2
  provider: ^6.1.5+1
  intl: any
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  coverage: ^1.15.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
