name: full_layout
description: "CLI to generate Flutter projects with a full layout template."
version: 1.1.2
repository: https://github.com/carlosparra1998/flutter_full_layout
homepage: https://github.com/carlosparra1998/flutter_full_layout

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  flutter_full_layout:

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
